# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1125, 804)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1161, 811))
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(360, 70, 761, 651))
        self.frame.setStyleSheet("background-image:url(..RD2.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_left = QtWidgets.QPushButton(self.frame)
        self.bt_left.setGeometry(QtCore.QRect(0, 230, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.bt_left.setFont(font)
        self.bt_left.setStyleSheet("")
        self.bt_left.setObjectName("bt_left")
        self.bt_rigth = QtWidgets.QPushButton(self.frame)
        self.bt_rigth.setGeometry(QtCore.QRect(630, 230, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.bt_rigth.setFont(font)
        self.bt_rigth.setStyleSheet("")
        self.bt_rigth.setObjectName("bt_rigth")
        self.bt_unlock = QtWidgets.QPushButton(self.frame)
        self.bt_unlock.setGeometry(QtCore.QRect(130, 310, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        self.bt_unlock.setFont(font)
        self.bt_unlock.setObjectName("bt_unlock")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(0, 230, 761, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(40)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.bt_left.raise_()
        self.bt_rigth.raise_()
        self.bt_unlock.raise_()
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(1000, 30, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:transparent;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(1000, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.barra = QtWidgets.QWidget(self.widget)
        self.barra.setGeometry(QtCore.QRect(0, 0, 361, 811))
        self.barra.setStyleSheet("")
        self.barra.setObjectName("barra")
        self.label = QtWidgets.QLabel(self.barra)
        self.label.setGeometry(QtCore.QRect(0, 60, 351, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.barra)
        self.label_4.setGeometry(QtCore.QRect(10, 640, 351, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.barra)
        self.label_5.setGeometry(QtCore.QRect(20, 420, 331, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.barra)
        self.label_6.setGeometry(QtCore.QRect(20, 490, 331, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(29)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.barra)
        self.label_7.setGeometry(QtCore.QRect(20, 710, 331, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(29)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.bt_play = QtWidgets.QPushButton(self.widget)
        self.bt_play.setGeometry(QtCore.QRect(790, 720, 331, 91))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(24)
        self.bt_play.setFont(font)
        self.bt_play.setStyleSheet("background-color:white;")
        self.bt_play.setObjectName("bt_play")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.bt_left.setText(_translate("Dialog", "<"))
        self.bt_rigth.setText(_translate("Dialog", ">"))
        self.bt_unlock.setText(_translate("Dialog", "Desbloquear"))
        self.label_8.setText(_translate("Dialog", "Bloqueado"))
        self.label_3.setText(_translate("Dialog", "1000"))
        self.label_2.setText(_translate("Dialog", "Coins"))
        self.label.setText(_translate("Dialog", "SpaceShipPy"))
        self.label_4.setText(_translate("Dialog", "Ultima Pontuação"))
        self.label_5.setText(_translate("Dialog", "Pontuação Maxima"))
        self.label_6.setText(_translate("Dialog", "1000"))
        self.label_7.setText(_translate("Dialog", "1450"))
        self.bt_play.setText(_translate("Dialog", "Play"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

