# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(1131, 804)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setWindowTitle("")
        Dialog.setWindowOpacity(1.0)
        Dialog.setToolTip("")
        Dialog.setStatusTip("")
        Dialog.setWhatsThis("")
        Dialog.setStyleSheet("")
        Dialog.setWindowFilePath("")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1161, 811))
        self.widget.setObjectName("widget")
        self.barra = QtWidgets.QWidget(self.widget)
        self.barra.setGeometry(QtCore.QRect(0, 0, 1131, 71))
        self.barra.setStyleSheet("")
        self.barra.setObjectName("barra")
        self.label = QtWidgets.QLabel(self.barra)
        self.label.setGeometry(QtCore.QRect(30, 10, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ls_icon = QtWidgets.QLabel(self.barra)
        self.ls_icon.setGeometry(QtCore.QRect(810, 0, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.ls_icon.setFont(font)
        self.ls_icon.setStyleSheet("color:#0d111c;")
        self.ls_icon.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.ls_icon.setObjectName("ls_icon")
        self.label_3 = QtWidgets.QLabel(self.barra)
        self.label_3.setGeometry(QtCore.QRect(690, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:black;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.barra)
        self.label_2.setGeometry(QtCore.QRect(690, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:black;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.bs_icon = QtWidgets.QLabel(self.barra)
        self.bs_icon.setGeometry(QtCore.QRect(890, 0, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.bs_icon.setFont(font)
        self.bs_icon.setStyleSheet("color:#0d111c;")
        self.bs_icon.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bs_icon.setObjectName("bs_icon")
        self.lb_exit = QtWidgets.QPushButton(self.barra)
        self.lb_exit.setGeometry(QtCore.QRect(1050, -1, 81, 73))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.lb_exit.setFont(font)
        self.lb_exit.setFlat(True)
        self.lb_exit.setObjectName("lb_exit")
        self.bt_store = QtWidgets.QPushButton(self.barra)
        self.bt_store.setGeometry(QtCore.QRect(970, -1, 81, 73))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.bt_store.setFont(font)
        self.bt_store.setFlat(True)
        self.bt_store.setObjectName("bt_store")
        self.bt_play = QtWidgets.QPushButton(self.widget)
        self.bt_play.setGeometry(QtCore.QRect(790, 720, 341, 91))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.bt_play.setFont(font)
        self.bt_play.setStyleSheet("background-color:white;")
        self.bt_play.setFlat(True)
        self.bt_play.setObjectName("bt_play")
        self.nivelframe = QtWidgets.QFrame(self.widget)
        self.nivelframe.setGeometry(QtCore.QRect(0, 70, 1131, 651))
        self.nivelframe.setStyleSheet("")
        self.nivelframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nivelframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nivelframe.setObjectName("nivelframe")
        self.bt_left_2 = QtWidgets.QPushButton(self.nivelframe)
        self.bt_left_2.setGeometry(QtCore.QRect(-2, 0, 141, 651))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.bt_left_2.setFont(font)
        self.bt_left_2.setStyleSheet("")
        self.bt_left_2.setIconSize(QtCore.QSize(26, 16))
        self.bt_left_2.setDefault(False)
        self.bt_left_2.setFlat(True)
        self.bt_left_2.setObjectName("bt_left_2")
        self.bt_unlock_2 = QtWidgets.QPushButton(self.nivelframe)
        self.bt_unlock_2.setGeometry(QtCore.QRect(140, 0, 141, 651))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.bt_unlock_2.setFont(font)
        self.bt_unlock_2.setFlat(True)
        self.bt_unlock_2.setObjectName("bt_unlock_2")
        self.bt_right_2 = QtWidgets.QPushButton(self.nivelframe)
        self.bt_right_2.setGeometry(QtCore.QRect(984, 0, 141, 651))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.bt_right_2.setFont(font)
        self.bt_right_2.setStyleSheet("")
        self.bt_right_2.setIconSize(QtCore.QSize(26, 16))
        self.bt_right_2.setDefault(False)
        self.bt_right_2.setFlat(True)
        self.bt_right_2.setObjectName("bt_right_2")
        self.line_2 = QtWidgets.QFrame(self.nivelframe)
        self.line_2.setGeometry(QtCore.QRect(0, 0, 1125, 2))
        self.line_2.setAutoFillBackground(False)
        self.line_2.setStyleSheet("color:rgb(184, 184, 184)")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Dialog", "SpaceShipPY"))
        self.ls_icon.setText(_translate("Dialog", "1000"))
        self.label_3.setText(_translate("Dialog", "1000"))
        self.label_2.setText(_translate("Dialog", "Coins"))
        self.bs_icon.setText(_translate("Dialog", "1000"))
        self.lb_exit.setText(_translate("Dialog", "Sair"))
        self.bt_store.setText(_translate("Dialog", "Loja"))
        self.bt_play.setText(_translate("Dialog", "Começar"))
        self.bt_left_2.setText(_translate("Dialog", "Anterior"))
        self.bt_unlock_2.setText(_translate("Dialog", "Desbloquear"))
        self.bt_right_2.setText(_translate("Dialog", "Seguinte"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

